### ISSUE TITLE
HW GL_SELECT does not support draw mode GL_LINES_ADJACENCY

### ISSUE THREAD

**Issue by kdaic** [mi-lib/roki-gl#10]
I've been getting the following error on my laptop (DELL XPS13) for some time now.

```
HW GL_SELECT does not support draw mode GL_LINES_ADJACENCY
```

Althogh I've been getting the error (on DELL XPS13), but since I was able to execute it, I didn't deal with it and put it off,
But while investigating the other issue, I noticed that the spherical part of link1 of the puma.ztk model was no longer being drawn. Hmm...

**Comment by zhidao** [comment]
@kdaic 
GL_LINES_ADJACENCY doesn't appear in the current RoKi-GL. It might be because of GL_QUADS, which is outdated in OpenGL 3.0. I've replaced all GL_QUADS and GL_QUAD_STRIP to GL_TRIANGLE_STRIP. Please check if your problem is resolved with this revision.

**Comment by kdaic** [comment]
Thank you for your quick response.  
I imported your updated main branch into my working branch and checked it.  
Fortunately, the above error no longer appeared !!  
That helps a lot !  

I think it's OK to close this PR.
