### ISSUE TITLE
A suggestion to take out selection buffer from rkglFrameHandleSelect()

### ISSUE THREAD

**Issue by zhidao** [mi-lib/roki-gl#4]
@kdaic 
As for `rkglFrameHandle`, I concealed the selection buffer in `rkglFrameHandleSelect()` as
```C
void rkglFrameHandleSelect(rkglFrameHandle *handle, rkglCamera *cam, int x, int y, void (* draw_func)(void))
{
  GLuint selbuf[BUFSIZ];
  GLuint *ns;

  rkglFrameHandleUnselect( handle );
  if( !( ns = rkglFindNearest( selbuf,
                rkglSelect( cam, draw_func, selbuf, BUFSIZ, x, y, 1, 1 ) ) ) ) return;
  ...
}
```
However, I noticed that you might want to share the selection buffer with other functions in your program.
So, I'm thinking of changing the specification as follows.
 - Define a class `rkglSelectionBuffer` to manage the buffer, the size of buffer, and the number of hits
 - Call `rkglSelect()` outside of `rkglFrameHandleSelect()`, and update an instance of `rkglSelectionBuffer`
 - Hand over the updated instance to `rkglFrameHandleSelect()`
What do you think about this idea?

**Comment by kdaic** [comment]
@zhidao  
Thank you for your concern about the selection buffer.  
As you said, the selection buffer was currently inaccessible within the library, so it was a bit of a problem that I couldn't draw and select rkChain and FramHandle at the same time.  
To deal with this, we managed the selection buffer by dividing the drawing order. But this will become troblesome as the number of objects increases.  
So I agree with your suggestion to make the selection buffer a new external data ``rkglSelectionBuffer``.

**Comment by zhidao** [comment]
I've merged the above implementation to the latest main branch.
Please refer example/select/select_buffer_test.c, example/chain/select_test.c, and example/shape/nurbs_2d_select_test.c for how to use it.
