### ISSUE TITLE
Abolish rkglChainNamedDraw()

### ISSUE THREAD

**Issue by zhidao** [mi-lib/roki-gl#5]
I'd like to abolish `rkglChainNamedDraw()` since it is not only `rkglChain` but also any objects that need names for selection. Instead, I'm thinking of defining `rkglChainSetName()`, which can be combined with `rkglChainDraw()` to make it available for selection. This idea is implemented in feature/name_for_selection branch. Please check it out.

**Comment by kdaic** [comment]
@zhidao  
Thank you for your concern about the selection buffer.  
As you said, the selection buffer was currently inaccessible within the library, so it was a bit of a problem that I couldn't draw and select rkChain and FramHandle at the same time.  
To deal with this, we managed the selection buffer by dividing the drawing order. But this will become troblesome as the number of objects increases.  
So I agree with your suggestion to make the selection buffer a new external data ``rkglSelectionBuffer``.

**Comment by zhidao** [comment]
I've merged the above modification to the latest main branch.
