### ISSUE TITLE
From GLUT to GLFW

### ISSUE THREAD

**Issue by kdaic** [mi-lib/roki-gl#6]
The GLUT library seems to have some bugs whch glutSwapBuffers() seems to allow collisions in critical sections of parallel thread processing.  
On one of my machines, a core dump occurred while executing memset() calculations on the main thread when a GLUT thread is running in another thread.  I temporarily attach a mutex lock, this core dump no longer occurs. 
This may be a machine-specific issue that is responsible for CPU optimization such as AVX operations in memset().  
On the other hand, when I tried the same implementation using GLFW, no core dump occurred.  
GLUT seems to have not been maintained for a long time. But GLFW is still being updated at December 2023 and appears to be robust against bugs.

I would like to suggest changging the OpenGL multi-platform utility library from GLUT to GLFW.

GLFW's License is [zlib/libpng License](https://en.wikipedia.org/wiki/Zlib_License).

I push roki_glfw.h/c at the branch feature/add_roki-glfw.  
I'm trying to implement the same functionality as the original roki_glut.h/c, but I don't know much about the original.   
Please check it.

**Comment by zhidao** [comment]
I think this issue can be closed.

**Comment by kdaic** [comment]
It's OK to close this PR. Thank you for making GLFW available.
